### ISSUE TITLE
Nested Flexible Content is not editable inside the modal window

### ISSUE THREAD

**Issue by VladNov** [edirpedro/acf-flexible-content-modal#1]
I'm using nested flexible content, but inside the modal window the fields are not editable and are not visible, it shows the parent field title instead.

Nested FC field is for a column layout. For example i add the parent field Two Columns and and then inside each column i can add other fields.

**Nested Fields:**
![screen shot 2016-11-04 at 11 26 46](https://cloud.githubusercontent.com/assets/2650362/20000918/7ce61a34-a282-11e6-9ed1-372e024052ee.png)

**Result:**
![screen shot 2016-11-04 at 11 32 46](https://cloud.githubusercontent.com/assets/2650362/20000925/80fdf3f8-a282-11e6-92eb-42c08b0b5990.png)

It's an awesome and very needed plugin!

**Comment by edirpedro** [comment]
I found some CSS problems on ACF plugin when trying to nest the FC field, this means that FC field is not intended to be nested like the Repeater field. The tooltip is also a problem inside the modal window, because the script behind it won't adjust the position of that list on screen, making the modal hiding part of the tooltip if it exceeds the screen limits.

Also your page builder idea will not able the user to move a FC item from column one to column two, drag and drop won't work in this situation.

Test it downloading this file, just remove the name "-nested-fc" from the folder name and update your plugin. Then tell me if it's working as expected.
https://github.com/edirpedro/acf-flexible-content-modal/archive/nested-fc.zip

**Comment by VladNov** [comment]
Hi Edir,

This version fixed the issue! Thank you.

It's perfectly fine that i can't drag fields between the columns. It suppose to work like parallel content.

Do you accept donations for this plugin and if yes, where can i make it?

**Comment by edirpedro** [comment]
Ok, the solution is not good enough so i'll check that again before launch the update.

If you really want to make a donation, click on the button at the readme page.
https://github.com/edirpedro/acf-flexible-content-modal

**Comment by VladNov** [comment]
One suggestion. Change the modal title icon class from `-cancel` to `-check grey`, it makes the icon as a confirmation: Done editing and click confirm to save the changes.

![screen shot 2016-11-05 at 02 14 40](https://cloud.githubusercontent.com/assets/2650362/20026007/af240170-a2fd-11e6-9916-1dbcf791d165.png)
