### ISSUE TITLE
problem with ACF 5.6

### ISSUE THREAD

**Issue by quartopianodesign** [edirpedro/acf-flexible-content-modal#6]
Hi edirpedro,
With the update of acf 5.6 it is no longer possible to edit the fields within the modal window (eg: Flexible content).
Do you think there will be an update soon?

thank you so much

**Comment by edirpedro** [comment]
I've tested here and everything is working fine, with ACF 5.6 and WP 4.8. Can you provide me a step by step or record a video? But before doing that, check if one of the other plugins you are using is causing this failure.

**Comment by quartopianodesign** [comment]
Hi,
Attach 3 screenshots to let you know the problem with ACF 5.5.14 and ACF 5.6.
Wp 4.8 and plugins you always see on the screenshot.
I hope it is clear.
Thank you
![schermata 2017-07-27 alle 09 30 16](https://user-images.githubusercontent.com/400949/28659681-9e80260e-72b0-11e7-85e6-22273699bed9.png)
![schermata 2017-07-27 alle 09 31 15](https://user-images.githubusercontent.com/400949/28659682-9e8226ca-72b0-11e7-9b35-d00e8eadaa84.png)
![schermata 2017-07-27 alle 09 38 13](https://user-images.githubusercontent.com/400949/28659683-9e828de0-72b0-11e7-9ad2-89da9f353391.png)

**Comment by edirpedro** [comment]
I tried to reproduce your error but I got no errors editing any field inside an FC or a nested FC field. Please follow theses instructions:

First: Check if another plugin is causing this problem. Disable everything and start enabling each plugin one by one and testing, you start with ACF Pro only, then add ACF FC Modal and so on.

Second: The problem is not another plugin. Please, create a simple form on ACF to simulate the error, then export this form in JSON format and send it to me so I can import here to make some tests. Describe to me how to use it to reproduce the error.

**Comment by edirpedro** [comment]
@qurtopianodesign I found some issue and made a fix, can you please download this file and update your copy to test and see if your problem still happens? Download this file and change the folder name `acf-flexible-content-modal-master` to `acf-flexible-content-modal` before update your plugin.

https://github.com/edirpedro/acf-flexible-content-modal/archive/master.zip

**Comment by quartopianodesign** [comment]
Great, now it works!

**Comment by edirpedro** [comment]
Thank you qurtopianodesign for your help. I'm sorry that takes too long, I was busy with some projects.
